import type { PaymentWithDetails } from '@/lib/payments-utils'
import type { PropertyWithDetails } from '@/lib/properties-utils'
import type { TenantWithDetails } from '@/lib/tenants-utils'
import type { Ticket } from '@/types'

export const devPayments: PaymentWithDetails[] = [
  {
    id: 'pay-1',
    type: 'Rental',
    property: 'A-101',
    property_id: 'prop-1',
    room: 'Master Bedroom',
    room_id: 'room-1',
    lease_id: 'lease-1',
    lease_reference_id: 'LS-2025-001',
    due_date: '2025-02-05',
    issued_at: '2025-01-05T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 2500,
    status: 'Paid',
    payment_percentage: 100,
    remaining_amount: 0,
    has_pending_payments: false,
    tenant_name: 'Ahmad bin Ali',
    tenant_picture: '',
    tenant_color: '#3B82F6',
    latest_payment_timestamp: '2025-02-05T10:30:00Z',
    payment_evidence: null,
    late_payment_charges: [],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-2',
    type: 'Rental',
    property: 'B-201',
    property_id: 'prop-3',
    room: 'Master Bedroom',
    room_id: 'room-3',
    lease_id: 'lease-2',
    lease_reference_id: 'LS-2025-002',
    due_date: '2025-02-01',
    issued_at: '2025-01-01T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 1800,
    status: 'Paid Late',
    payment_percentage: 100,
    remaining_amount: 0,
    has_pending_payments: false,
    tenant_name: 'Siti Aminah binti Omar',
    tenant_picture: '',
    tenant_color: '#10B981',
    latest_payment_timestamp: '2025-02-03T14:20:00Z',
    payment_evidence: null,
    late_payment_charges: [{ days_after_due: 2, amount: 50 }],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-3',
    type: 'Rental',
    property: 'A-101',
    property_id: 'prop-1',
    room: 'Bedroom 2',
    room_id: 'room-2',
    lease_id: 'lease-4',
    lease_reference_id: 'LS-2024-005',
    due_date: '2025-02-10',
    issued_at: '2025-01-10T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 2000,
    status: 'Pending',
    payment_percentage: 0,
    remaining_amount: 2000,
    has_pending_payments: true,
    tenant_name: 'Raj Kumar',
    tenant_picture: '',
    tenant_color: '#F59E0B',
    latest_payment_timestamp: '2025-01-10T09:15:00Z',
    payment_evidence: null,
    late_payment_charges: [],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-4',
    type: 'Electricity_Bill',
    property: 'A-101',
    property_id: 'prop-1',
    room: 'Whole unit',
    room_id: null,
    lease_id: 'lease-1',
    lease_reference_id: 'LS-2025-001',
    due_date: '2025-02-15',
    issued_at: '2025-01-15T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 350,
    status: 'Overdue',
    payment_percentage: 0,
    remaining_amount: 350,
    has_pending_payments: true,
    tenant_name: 'Ahmad bin Ali',
    tenant_picture: '',
    tenant_color: '#3B82F6',
    latest_payment_timestamp: '2024-12-15T11:00:00Z',
    payment_evidence: null,
    late_payment_charges: [{ days_after_due: 10, amount: 100 }],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-5',
    type: 'Lease_Initial_Charges',
    property: 'D-401',
    property_id: 'prop-5',
    room: 'Whole unit',
    room_id: null,
    lease_id: 'lease-3',
    lease_reference_id: 'LS-2025-003',
    due_date: '2024-12-20',
    issued_at: '2024-12-20T10:00:00Z',
    recurring_pattern: 'One-time',
    recurring_pattern_description: 'Security Deposit',
    amount: 6400,
    status: 'Paid',
    payment_percentage: 100,
    remaining_amount: 0,
    has_pending_payments: false,
    tenant_name: 'John Smith',
    tenant_picture: '',
    tenant_color: '#8B5CF6',
    latest_payment_timestamp: '2024-12-20T16:45:00Z',
    payment_evidence: null,
    late_payment_charges: [],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-6',
    type: 'Rental',
    property: 'A-101',
    property_id: 'prop-1',
    room: 'Master Bedroom',
    room_id: 'room-1',
    lease_id: 'lease-1',
    lease_reference_id: 'LS-2025-001',
    due_date: '2025-03-05',
    issued_at: '2025-02-05T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 2500,
    status: 'Pending',
    payment_percentage: 0,
    remaining_amount: 2500,
    has_pending_payments: true,
    tenant_name: 'Ahmad bin Ali',
    tenant_picture: '',
    tenant_color: '#3B82F6',
    latest_payment_timestamp: '2025-02-05T10:30:00Z',
    payment_evidence: null,
    late_payment_charges: [],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  },
  {
    id: 'pay-7',
    type: 'Parking',
    property: 'B-201',
    property_id: 'prop-3',
    room: 'Whole unit',
    room_id: null,
    lease_id: 'lease-2',
    lease_reference_id: 'LS-2025-002',
    due_date: '2025-02-01',
    issued_at: '2025-01-01T10:00:00Z',
    recurring_pattern: 'Recurring',
    recurring_pattern_description: 'Monthly',
    amount: 200,
    status: 'Partially Paid',
    payment_percentage: 50,
    remaining_amount: 100,
    has_pending_payments: true,
    tenant_name: 'Siti Aminah binti Omar',
    tenant_picture: '',
    tenant_color: '#10B981',
    latest_payment_timestamp: '2025-02-01T08:00:00Z',
    payment_evidence: null,
    late_payment_charges: [],
    can_edit: true,
    fpx_cooling_remaining_minutes: null
  }
]

export const devProperties: PropertyWithDetails[] = [
  {
    id: 'prop-1',
    code: 'A-101',
    address: '123 Jalan Sultan, Kuala Lumpur',
    project: 'Sunset Residences',
    type: 'Condominium',
    status: 'Occupied',
    isBooked: false,
    features: { wifi: true, water_heater: true }
  },
  {
    id: 'prop-2',
    code: 'A-102',
    address: '125 Jalan Sultan, Kuala Lumpur',
    project: 'Sunset Residences',
    type: 'Condominium',
    status: 'Vacant',
    isBooked: false
  },
  {
    id: 'prop-3',
    code: 'B-201',
    address: '456 Jalan Ampang, Kuala Lumpur',
    project: 'Sunset Residences',
    type: 'Apartment',
    status: 'Occupied',
    isBooked: false,
    features: { wifi: true, cleaning_service: true }
  },
  {
    id: 'prop-4',
    code: 'C-301',
    address: '789 Jalan Tun Razak, Selangor',
    project: 'Green Valley Apartments',
    type: 'Studio',
    status: 'Pending_Inspection',
    isBooked: false
  },
  {
    id: 'prop-5',
    code: 'D-401',
    address: '321 Jalan Bukit Bintang, Kuala Lumpur',
    project: 'City Center Condos',
    type: 'Penthouse',
    status: 'Under_Preparation',
    isBooked: false,
    features: { wifi: true, water_heater: true, dryer: true }
  },
  {
    id: 'prop-6',
    code: 'E-501',
    address: '654 Jalan Imbi, Kuala Lumpur',
    project: 'City Center Condos',
    type: 'Condominium',
    status: 'Vacant',
    isBooked: false
  }
]

export const devTenants: TenantWithDetails[] = [
  {
    id: 'tenant-1',
    type: 'Individual',
    profile_pic: null,
    profile_thumb: null,
    first_name: 'Ahmad',
    last_name: 'bin Ali',
    identity_type: 'mykad',
    identity_number: '800101-10-5555',
    phone_number: '+6012-345-6789',
    email: 'ahmad.ali@email.com',
    accountStatus: 'Activated',
    inviteSent: true,
    activeLeaseCount: 1,
    activeBookingCount: 0,
    rental_status: 'Renting'
  },
  {
    id: 'tenant-2',
    type: 'Individual',
    profile_pic: null,
    profile_thumb: null,
    first_name: 'Siti Aminah',
    last_name: 'binti Omar',
    identity_type: 'mykad',
    identity_number: '850505-08-4444',
    phone_number: '+6013-456-7890',
    email: 'siti.aminah@email.com',
    accountStatus: 'Activated',
    inviteSent: true,
    activeLeaseCount: 1,
    activeBookingCount: 0,
    rental_status: 'Renting'
  },
  {
    id: 'tenant-3',
    type: 'Individual',
    profile_pic: null,
    profile_thumb: null,
    first_name: 'John',
    last_name: 'Smith',
    identity_type: 'passport',
    identity_number: 'A12345678',
    phone_number: '+6014-567-8901',
    email: 'john.smith@email.com',
    accountStatus: 'Activated',
    inviteSent: false,
    activeLeaseCount: 0,
    activeBookingCount: 1,
    rental_status: 'Not Renting'
  },
  {
    id: 'tenant-4',
    type: 'Individual',
    profile_pic: null,
    profile_thumb: null,
    first_name: 'Maria',
    last_name: 'Garcia',
    identity_type: 'passport',
    identity_number: 'B98765432',
    phone_number: '+6017-678-9012',
    email: 'maria.garcia@email.com',
    accountStatus: 'Pending',
    inviteSent: true,
    activeLeaseCount: 0,
    activeBookingCount: 0,
    rental_status: 'Not Renting'
  },
  {
    id: 'tenant-5',
    type: 'Individual',
    profile_pic: null,
    profile_thumb: null,
    first_name: 'Raj',
    last_name: 'Kumar',
    identity_type: 'mykad',
    identity_number: '880404-16-1111',
    phone_number: '+6019-789-0123',
    email: 'raj.kumar@email.com',
    accountStatus: 'Activated',
    inviteSent: true,
    activeLeaseCount: 1,
    activeBookingCount: 0,
    rental_status: 'Renting'
  }
]

export const devTickets: Ticket[] = [
  {
    id: 'TK-2025-001',
    ticket_id: 'ticket-1',
    type: 'Maintenance',
    title: 'Air conditioner not cooling',
    description: 'The air conditioner in the master bedroom is not cooling properly. It makes unusual noises.',
    property: 'A-101',
    room: 'Master Bedroom',
    tenant_name: 'Ahmad bin Ali',
    tenant_picture: '',
    issue_timestamp: '2025-01-10T09:30:00Z',
    staff_name: 'Mike Johnson',
    staff_picture: '',
    assigner_name: 'Admin',
    assignment_timestamp: '2025-01-10T10:00:00Z',
    status: 'In Progress'
  },
  {
    id: 'TK-2025-002',
    ticket_id: 'ticket-2',
    type: 'Maintenance',
    title: 'Leaking faucet in bathroom',
    description: 'The bathroom faucet is leaking continuously. Water is dripping even when turned off.',
    property: 'B-201',
    room: 'Whole unit',
    tenant_name: 'Siti Aminah binti Omar',
    tenant_picture: '',
    issue_timestamp: '2025-01-12T14:15:00Z',
    staff_name: 'Sarah Lee',
    staff_picture: '',
    assigner_name: 'Admin',
    assignment_timestamp: '2025-01-12T15:00:00Z',
    status: 'Open'
  },
  {
    id: 'TK-2025-003',
    ticket_id: 'ticket-3',
    type: 'Maintenance',
    title: 'Light fixture not working',
    description: 'The ceiling light in the living room is not working. Changed bulb but still no power.',
    property: 'C-301',
    room: 'Whole unit',
    tenant_name: 'John Smith',
    tenant_picture: '',
    issue_timestamp: '2025-01-15T11:00:00Z',
    status: 'Open',
    assignment_timestamp: '2025-01-15T11:30:00Z'
  },
  {
    id: 'TK-2025-004',
    ticket_id: 'ticket-4',
    type: 'Maintenance',
    title: 'Door lock jammed',
    description: 'The main door lock is difficult to turn. Sometimes gets stuck.',
    property: 'A-101',
    room: 'Whole unit',
    tenant_name: 'Ahmad bin Ali',
    tenant_picture: '',
    issue_timestamp: '2025-01-08T16:30:00Z',
    staff_name: 'Mike Johnson',
    staff_picture: '',
    assigner_name: 'Admin',
    assignment_timestamp: '2025-01-08T17:00:00Z',
    status: 'Resolved'
  },
  {
    id: 'TK-2025-005',
    ticket_id: 'ticket-5',
    type: 'Aircon Top-Up',
    title: 'Request for aircon credit top-up',
    description: 'Need to add RM50 to aircon credit for unit B-201.',
    property: 'B-201',
    room: 'Whole unit',
    tenant_name: 'Siti Aminah binti Omar',
    tenant_picture: '',
    issue_timestamp: '2025-01-14T08:00:00Z',
    status: 'Open',
    assignment_timestamp: '2025-01-14T08:30:00Z'
  }
]
